# Generated by Django 6.0.4 on 2026-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MashoraDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("governorate", models.CharField(max_length=100)),
                ("governorate_code", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("area_code", models.CharField(max_length=100)),
                ("healthcare_ins", models.CharField(max_length=100)),
                ("healthcare_ins_code", models.CharField(max_length=100)),
            ],
        ),
    ]
